server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

logging:
  level:
    root: INFO
    com.ysb5397: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hybrid_map?useSSl=false&serverTimezone=Asia/Seoul
    username: root
    password: asd1234

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10

    defer-datasource-initialization: true

jwt:
  secret: 'a0Z0aEFtTklTNEtSVHlYcUNzN3JvN2N3enVqME1teXIyKzFLcHpVdldhQjZONk52VjJjYlZLUHlKWW53bw=='
  expiration-in-ms: 3600000 # 1시간

login:
  # naver: ""
  kakao:
    key: "nJyO29a2pfOmnU9TFMRF55Fnf06MREdT"
    redirect-uri: "http://localhost:8080/api/users/login/kakao/auth"